#!/usr/bin/env python

# shNode Module: tracer/data
# ouput status of Tracer Solar Charge Controller in XML format

import serial, jxmlease
from tracer import Tracer, TracerSerial, QueryCommand

# Set Serial interface path
s_path = '/dev/ttyS0' # ttyS0 w/ Bluetooth ttyAMA0 w/o

ser = serial.Serial(s_path, 9600, timeout = 1)

tracer = Tracer(0x16)
t_ser = TracerSerial(tracer, ser)
query = QueryCommand()
t_ser.send_command(query)
result = t_ser.receive_result()

# format the output string for xml parsing
formatted = str(result).replace(': ', '\': \'')
formatted = formatted.replace('QueryResult{', '{\'tracer\': {\'')
formatted = formatted.replace(', ', '\', \'')
formatted = formatted.replace('}', '\'}}')

print(jxmlease.emit_xml(eval(formatted)))
